# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class about_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_top.setStyleSheet("background-color: rgb(130, 130, 130);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_top)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_title.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"padding: 10px;")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_content = QtWidgets.QFrame(self.centralwidget)
        self.frame_content.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_content)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.frame_content)
        self.frame_credits = QtWidgets.QFrame(self.centralwidget)
        self.frame_credits.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_credits.setStyleSheet("background-color: rgb(215, 215, 215);")
        self.frame_credits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_credits.setObjectName("frame_credits")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_credits)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_credits = QtWidgets.QLabel(self.frame_credits)
        self.label_credits.setStyleSheet("margin-left: 5px;\n"
"color: rgb(100, 100, 100);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_4.addWidget(self.label_credits)
        self.label_version = QtWidgets.QLabel(self.frame_credits)
        self.label_version.setStyleSheet("margin-right: 5px;\n"
"color: rgb(100, 100, 100);")
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_4.addWidget(self.label_version)
        self.verticalLayout.addWidget(self.frame_credits)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Conversor e Equalizador de Imagens"))
        self.label_title.setText(_translate("MainWindow", "Conversor e Equalizador de Imagens"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">O </span><span style=\" font-size:11pt; font-weight:600;\">Conversor e Equalizador de Imagens</span><span style=\" font-size:11pt;\"> é um software desenvolvido pelos acadêmicos Angelo José Orssatto, Lucas Veit de Sá e Mateus Karvat Camara, do Bacharelado de Ciência da Computação da Universidade Estadual do Oeste do Paraná, como componente avaliativo da disciplina de Processamento de Imagens Digitais, ministrada pelos professores doutores Adair Santa Catarina e André Luiz Brun.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Este programa realiza a equalização do canal Y na representação de cores YCbCr. Primeiramente, é realizada a conversão da imagem de RGB para YCbCr, seguida da equalização propriamente dita e então a reconversão para RGB.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">O botão &quot;</span><span style=\" font-size:11pt; font-weight:600;\">Abrir Imagem</span><span style=\" font-size:11pt;\">&quot; abre uma caixa de diálogo na qual você pode escolher a imagem a ser equalizada.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Após abrir a imagem, ao apertar o botão &quot;</span><span style=\" font-size:11pt; font-weight:600;\">Converter e Equalizar</span><span style=\" font-size:11pt;\">&quot; a equalização da imagem é efetuada. Como o processo envolve 3 operações em imagens, ele pode levar alguns segundos, dependendo das dimensões da imagem escolhida. A imagem final é exibida assim que o processo é encerrado.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Após a conversão, basta apertar o botão &quot;</span><span style=\" font-size:11pt; font-weight:600;\">Salvar</span><span style=\" font-size:11pt;\">&quot; para salvar a imagem final em disco. O programa salvará a imagem final na mesma pasta em que se encontra o programa.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Para os usuários interessados em verificar o funcionamento do software &quot;por trás dos panos&quot;, o botão &quot;</span><span style=\" font-size:11pt; font-weight:600;\">Mostrar gráficos</span><span style=\" font-size:11pt;\">&quot; exibe a curva de frequência acumulada utilizada durante a equalização, além dos histogramas dos canais Y, R, G e B antes e após a equalização do canal Y.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Para quaisquer dúvidas adicionais, fique à vontade para enviar um e-mail para mkarvat@gmail.com, angelojorssatto@hotmail.com ou lucas-cs1998@hotmail.com.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Disponível em: https://github.com/AngeloOrssatto/conversor_equalizador_ycbcr</span></p></body></html>"))
        self.label_credits.setText(_translate("MainWindow", "Desenvolvido por Orssatto, Camara, Veit"))
        self.label_version.setText(_translate("MainWindow", "v 1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = about_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
